version: "3.8"
services:

  web:
    image: python:buster
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=truetone
    ports:
      - 5000:5000
    command: bash -c "pip install -e . && flask run --host=0.0.0.0"
