version: "3.8"
services:

  web:
    image: python:buster
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000
    command: bash -c "export FLASK_APP=./app/app.py && flask run --host=0.0.0.0"
